extensions:
    pimgento-csv-family-export-edit-permission:
        module: pimee/common/tab/permission
        parent: pimgento-csv-family-export-edit-tabs
        targetZone: container
        aclResourceId: pimee_importexport_import_profile_edit_permissions
        position: 115
        config:
            title: pimee_enrich.form.job_instance.tab.permission.title
            tabCode: pim-job-instance-permission

    pimgento-csv-family-export-show-permission:
        module: pimee/common/tab/permission
        parent: pimgento-csv-family-export-edit-tabs
        targetZone: container
        position: 115
        aclResourceId: pimee_importexport_import_profile_show_permissions
        config:
            title: pimee_enrich.form.job_instance.tab.permission.title
            tabCode: pim-job-instance-permission
            readOnly: true
